# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
cache: packages

r_packages:
  - covr
  - pkgdown
  - dplyr
  - ggplot2
  - viridis
  - tidyr
  - ggrepel
  - igraph

r_github_packages: dirkschumacher/rmpk.glpk

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libglpk-dev
    - g++-7

before_install:
  - export CXX17=g++-7

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script:
    - Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
